quicklogic: use dfflegalize
antmicro/yosys pull request #3
Opened 2020-11-27 16:38 UTC by Ravenslofty

Yosys has the `dfflegalize` pass to add inverters etc to the natively-supported DFF cell type. This can be used to automatically perform a lot of the mapping that was previously performed manually, so a lot of the techmap rules can be removed without any (intended) change in functionality.

2020-12-01 13:22 UTC, mkurc-ant requested changes

2020-12-01 13:22 UTC, mkurc-ant commented on techlibs/quicklogic/pp3_latches_map.v
> +module \$_DLATCH_P_ (E, D, Q);
I would be cautious with this change. The reason for having explicit LUT configurations for different latch variants is because the proprietary synthesis tool for EOS S3 implements them in this way. I see no reason why your approach wouldn't work but I'd rather consult that with QuickLogic people just to be sure.

Maybe we could split this PR into two: one for FFs and other for latches ?

2020-12-01 13:54 UTC, Ravenslofty commented on techlibs/quicklogic/pp3_latches_map.v
> +module \$_DLATCH_P_ (E, D, Q);
#6 has the flop mapping, then if you're happy with that I'll do a latch PR.

2020-12-02 12:52 UTC, Ravenslofty commented on techlibs/quicklogic/pp3_latches_map.v
> +module \$_DLATCH_P_ (E, D, Q);
#9 has the latch mapping.

2020-12-02 12:52 UTC, closed without merging